name: Build package
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-publish-package:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 20.0.1
        uses: actions/setup-java@v1
        with:
          java-version: 20.0.1
      - name: Build and deploy with Maven
        run: ./mvnw --no-transfer-progress clean -U deploy
